version: "2"

services:
    frontend:
        build: ./frontend
        command: tail -f /dev/null
        ports:
         - 80:80
         - 8000:8000
        volumes:
         - ./frontend:/opt/frontend
